import { useState, useEffect, useContext } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { jsPDF } from "jspdf";
import AuthContext from '../context/AuthContext';
import AIContext from '../context/AIContext';

export default function AppealEditor() {
    const { id } = useParams();
    const navigate = useNavigate();
    const [appeal, setAppeal] = useState(null);
    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);
    const [emailing, setEmailing] = useState(false);
    const [emailModalOpen, setEmailModalOpen] = useState(false);
    const { token, user } = useContext(AuthContext);
    const { setContextData } = useContext(AIContext);
    const [content, setContent] = useState('');
    const [status, setStatus] = useState('Draft');

    useEffect(() => {
        if (!token) return;

        fetch(`http://localhost:5000/appeals/${id}`, {
            headers: { 'x-auth-token': token }
        })
            .then(res => res.json())
            .then(data => {
                setAppeal(data);
                setContent(data.appeal_letter);
                setStatus(data.status || 'Draft');
                setContextData(prev => ({
                    ...prev,
                    appeal_id: data.id,
                    patient_name: data.patient_name,
                    denial_reason: data.denial_reason,
                    appeal_letter: data.appeal_letter
                }));
                setLoading(false);
            })
            .catch(err => {
                console.error(err);
                setLoading(false);
            });
    }, [id, token]);

    const handleSave = async () => {
        setSaving(true);
        try {
            const res = await fetch(`http://localhost:5000/appeals/${id}`, {
                method: 'PUT',
                headers: {
                    'Content-Type': 'application/json',
                    'x-auth-token': token
                },
                body: JSON.stringify({
                    appeal_letter: content,
                    patient_name: appeal.patient_name,
                    status: status
                })
            });

            if (res.ok) {
                navigate('/history');
            }
        } catch (err) {
            console.error(err);
            alert('Failed to save');
        } finally {
            setSaving(false);
        }
    };

    const handleDownload = () => {
        const doc = new jsPDF();
        doc.setFontSize(22);
        doc.setTextColor(40, 40, 40);
        doc.text("Appeal Letter", 105, 20, null, null, "center");
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`Patient: ${appeal.patient_name || 'Unknown'}`, 20, 35);
        doc.text(`Date: ${new Date().toLocaleDateString()}`, 190, 35, null, null, "right");
        doc.setDrawColor(200, 200, 200);
        doc.line(20, 40, 190, 40);
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
        const splitText = doc.splitTextToSize(content, 170);
        doc.text(splitText, 20, 50);
        const pageHeight = doc.internal.pageSize.height;
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text("Generated by ClaimHealth AI", 105, pageHeight - 10, null, null, "center");
        doc.save(`${appeal.patient_name || 'Appeal'}_Letter.pdf`);
    };

    const handleEmail = async (recipientEmail, emailSubject) => {
        if (!recipientEmail || !emailSubject) return;
        setEmailing(true);
        try {
            const res = await fetch('http://localhost:5000/email/send', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'x-auth-token': token
                },
                body: JSON.stringify({
                    to: recipientEmail,
                    subject: emailSubject,
                    appeal_text: content,
                    patient_name: appeal.patient_name
                })
            });
            const data = await res.json();
            if (res.ok) {
                alert('Email sent successfully!');
                setEmailModalOpen(false);
            } else {
                throw new Error(data.error);
            }
        } catch (err) {
            console.error(err);
            alert('Failed to send email: ' + err.message);
        } finally {
            setEmailing(false);
        }
    };

    if (loading) return (
        <div className="flex flex-col items-center justify-center h-full min-h-[400px]">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mb-4"></div>
            <p className="text-slate-500 font-medium">Loading appeal details...</p>
        </div>
    );

    if (!appeal) return (
        <div className="flex flex-col items-center justify-center h-full min-h-[400px] text-red-500">
            <svg className="w-12 h-12 mb-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
            <p className="font-medium">Appeal not found</p>
        </div>
    );

    return (
        <div className="h-[calc(100vh-8rem)] flex flex-col">
            <div className="flex justify-between items-center mb-6 shrink-0">
                <div className="flex items-center gap-4">
                    <button onClick={() => navigate('/history')} className="text-slate-500 dark:text-slate-400 hover:text-blue-600 dark:hover:text-blue-400 flex items-center gap-1 font-medium text-sm transition-colors">
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7"></path></svg>
                        Back
                    </button>
                    <div className="h-6 w-px bg-slate-200 dark:bg-slate-700"></div>
                    <div>
                        <h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-3">
                            {appeal.patient_name}
                            <span className="text-xs font-normal text-slate-500 bg-slate-100 dark:bg-slate-800 dark:text-slate-400 px-2 py-0.5 rounded border border-slate-200 dark:border-slate-700">
                                {appeal.denial_reason ? (appeal.denial_reason.length > 40 ? appeal.denial_reason.substring(0, 40) + '...' : appeal.denial_reason) : 'Denied'}
                            </span>
                        </h2>
                        <div className="mt-1 flex items-center gap-4">
                            <div className="flex items-center gap-2">
                                <span className="text-xs text-slate-500">Status:</span>
                                <select
                                    value={status}
                                    onChange={(e) => setStatus(e.target.value)}
                                    className={`text-xs font-semibold px-2 py-0.5 rounded border outline-none cursor-pointer ${status === 'Successful' ? 'bg-green-50 text-green-700 border-green-200 dark:bg-green-900/40 dark:text-green-400 dark:border-green-900' :
                                            status === 'Rejected' ? 'bg-red-50 text-red-700 border-red-200 dark:bg-red-900/40 dark:text-red-400 dark:border-red-900' :
                                                status === 'Sent' ? 'bg-blue-50 text-blue-700 border-blue-200 dark:bg-blue-900/40 dark:text-blue-400 dark:border-blue-900' :
                                                    'bg-slate-50 text-slate-700 border-slate-200 dark:bg-slate-800 dark:text-slate-300 dark:border-slate-700'
                                        }`}
                                >
                                    <option value="Draft">Draft</option>
                                    <option value="Sent">Sent</option>
                                    <option value="Successful">Successful</option>
                                    <option value="Rejected">Rejected</option>
                                </select>
                            </div>
                            <div className="text-xs text-slate-500 font-medium border-l border-slate-200 dark:border-slate-700 pl-4">
                                Amount: <span className="text-slate-900 dark:text-white">${appeal.claim_amount || '0.00'}</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="flex gap-3">
                    <button
                        onClick={() => setEmailModalOpen(true)}
                        disabled={emailing}
                        className="btn bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700"
                    >
                        {emailing ? 'Sending...' : (
                            <>
                                <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg>
                                Email Letter
                            </>
                        )}
                    </button>
                    <button
                        onClick={handleSave}
                        disabled={saving}
                        className="btn btn-primary"
                    >
                        {saving ? (
                            <>
                                <div className="animate-spin rounded-full h-4 w-4 border-2 border-white/30 border-b-white mr-2"></div>
                                Saving...
                            </>
                        ) : 'Save Changes'}
                    </button>
                    <button
                        onClick={handleDownload}
                        className="btn btn-secondary bg-white dark:bg-slate-800 text-slate-700 dark:text-white border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-700"
                    >
                        <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" /></svg>
                        Download PDF
                    </button>
                </div>
            </div>

            <div className="flex-1 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl shadow-sm overflow-hidden flex flex-col min-h-0">
                <div className="bg-slate-50 dark:bg-slate-900 border-b border-slate-200 dark:border-slate-700 px-4 py-2 flex gap-2 text-xs text-slate-600 dark:text-slate-400 font-medium shrink-0">
                    <span className="px-3 py-1.5 rounded-md bg-white dark:bg-slate-800 shadow-sm border border-slate-200 dark:border-slate-700 text-blue-700 dark:text-blue-400">Editor</span>
                    <span className="px-3 py-1.5 rounded-md hover:bg-slate-200 dark:hover:bg-slate-800 cursor-pointer transition-colors text-slate-500 dark:text-slate-500">Preview</span>
                </div>
                <div className="flex-1 relative">
                    <textarea
                        value={content}
                        onChange={(e) => setContent(e.target.value)}
                        className="absolute inset-0 w-full h-full p-8 text-slate-700 dark:text-slate-300 font-mono text-sm resize-none focus:outline-none leading-relaxed bg-white dark:bg-slate-800"
                        spellCheck="false"
                    />
                </div>
            </div>
            {/* Email Modal */}
            {emailModalOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm animate-in fade-in duration-200">
                    <div className="bg-white dark:bg-slate-800 rounded-xl shadow-2xl max-w-md w-full overflow-hidden border border-slate-200 dark:border-slate-700">
                        <div className="p-6 border-b border-slate-100 dark:border-slate-700">
                            <h3 className="text-lg font-bold text-slate-900 dark:text-white">Send Appeal via Email</h3>
                            <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">Send the appeal letter directly to the insurance provider.</p>
                        </div>

                        <form onSubmit={(e) => {
                            e.preventDefault();
                            const formData = new FormData(e.target);
                            handleEmail(formData.get('email'), formData.get('subject'));
                        }} className="p-6 space-y-4">
                            <div>
                                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Recipient Email</label>
                                <input
                                    type="email"
                                    name="email"
                                    required
                                    placeholder="insurance@example.com"
                                    className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 text-slate-900 dark:text-white focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 outline-none transition-all"
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Subject Line</label>
                                <input
                                    type="text"
                                    name="subject"
                                    required
                                    defaultValue={`Appeal for ${appeal.patient_name}`}
                                    className="w-full px-4 py-2 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 text-slate-900 dark:text-white focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 outline-none transition-all"
                                />
                            </div>

                            <div className="flex gap-3 pt-4">
                                <button
                                    type="button"
                                    onClick={() => setEmailModalOpen(false)}
                                    className="flex-1 px-4 py-2 rounded-lg border border-slate-200 dark:border-slate-600 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700 font-medium transition-colors"
                                >
                                    Cancel
                                </button>
                                <button
                                    type="submit"
                                    disabled={emailing}
                                    className="flex-1 px-4 py-2 rounded-lg bg-blue-600 hover:bg-blue-700 text-white font-medium shadow-lg shadow-blue-600/20 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex justify-center items-center"
                                >
                                    {emailing ? (
                                        <>
                                            <div className="w-4 h-4 border-2 border-white/30 border-b-white rounded-full animate-spin mr-2"></div>
                                            Sending...
                                        </>
                                    ) : 'Send Email'}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}

        </div>
    );
}
